[package]
name = "service-manager-test"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
service-manager = "0.8.0"
windows = {version = "0.61.1", features = ["Win32_UI_WindowsAndMessaging", "Win32_UI_Shell", "Win32_System_Console"] }
windows-service = "0.8.0"
